version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.3
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"
      - run:
          name: "Install Adonis CLI"
          command: sudo npm i -g @adonisjs/cli
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: "Create Environment file and Run migrations"
          command: |
            mv .env.example .env
            adonis migration:run
      - run:
          name: "Deploy to Heroku"
          command: |
            git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git
