version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.3
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"
      - run:
          name: "Install Adonis CLI"
          command: sudo npm i -g @adonisjs/cli
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: "Run migrations"
          command: adonis migration:run

      - heroku/deploy-via-git
